- name: Install-Gitlab
  hosts: server
  user: root
  roles:
    # for root
    - hostname
    - Packages
    - user
    # for user
    - mariadb
    - ruby
    - gitlab-shell
    - gitlab
    - gitlab-plugins
  vars:
    gitlab_version: 7-0-stable
