---
- name: Add User git
  user: name=git

- name: Copy .gitconfig
  template: src=.gitconfig dest=/home/git/.gitconfig mode=0664

- name: Copy /etc/sudoers.d/sudo_git
  template: src=sudo_git dest=/etc/sudoers.d/git mode=0440

- name: Create ~/.ssh
  file: path=/home/git/.ssh state=directory

- name: Copy ssh_pub_key
  shell: cp /root/.ssh/authorized_keys /home/git/.ssh/authorized_keys && chown git:git /home/git/.ssh/authorized_keys && chmod 600 /home/git/.ssh/authorized_keys

# Gitlab
- name: Template /etc/init.d/gitlab
  file: path=/etc/init.d/gitlab mode=0775 owner=git group=git
