---
- name: Template epel.repo
  template: src=epel.repo dest=/etc/yum.repos.d/epel.repo mode=0644

- name: Template remi.repo
  template: src=epel.repo dest=/etc/yum.repos.d/remi.repo mode=0644

- name: Template mariadb.repo
  template: src=mariadb.repo dest=/etc/yum.repos.d/mariadb.repo mode=0644

- name: Install(Group) development
  yum: pkg='@development' state=latest

- name: Install Vim
  yum: pkg={{ item }} state=installed
  with_items:
    - vim

- name: Install Git
  yum: pkg={{ item }} state=installed
  with_items:
    - git-all

- name: Install Ruby Dependency
  yum: pkg={{ item }} state=installed enablerepo=epel 
  with_items:
    - openssl-devel
    - zlib-devel
    - gdbm-devel
    - readline-devel
    - ncurses-devel
    - libffi-devel
    - libyaml-devel
    - libxml2-devel
    - libxslt-devel
    - libicu-devel
    - libcurl-devel
    - curl

- name: Install Redis
  yum: pkg={{ item }} state=installed enablerepo=remi enablerepo=epel
  with_items:
    - redis #in remi
    - gperftools-libs #in epel dependency
    - libunwind #in epql dependency
    - libunwind-devel #in epel ??

- name: Install MariaDB
  yum: pkg={{ item }} state=installed enablerepo=mariadb
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MariaDB-common
    - MariaDB-compat
    - MariaDB-devel
