---
- name: insert gem 'omniauth-redmine'
  lineinfile: dest={{ gitlab_dir }}/Gemfile state=present
              insertafter="^gem 'omniauth-github'" line="gem 'omniauth-redmine', :github => 'suer/omniauth-redmine'"
  remote_user: git

- name: bundle install
  command: chdir=~/gitlab bundle install --path .bundle --no-deployment --without development test mysql aws 
  remote_user: git

- name: modify oauth ebabled
  template: src=omniauth-redmine/gitlab.yml.j2 dest={{ gitlab_dir }}/config/gitlab.yml backup=yes
  remote_user: git

- name: restart gitlab
  service: name=gitlab state=restarted
