- name: Download rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv
  remote_user: git

- name: rbenv echo
  shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
  remote_user: git

- name: rbenv echo
  shell: echo 'eval "$(rbenv init -)"' >> ~/.bashrc
  remote_user: git

- name: Download ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  remote_user: git

- name: Install ruby-build
  shell: /bin/bash -c "export PREFIX=~/local/src/ &&  ~/.rbenv/plugins/ruby-build/install.sh" chdir=~/.rbenv/plugins/ruby-build
  remote_user: git

- name: Install Ruby
  shell: MAKE_OPTS="-j 4" rbenv install {{ ruby_ver }} -f -k
  remote_user: git

- name: rbenv global 
  shell: rbenv global {{ ruby_ver }}
  notify: rehash
  remote_user: git

- name: gem install
  shell: rbenv exec gem install bundler --no-ri --no-rdoc
  notify: rehash
  remote_user: git
